/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.StorageManager;
import control.Utils;
import dbmanager.DbManager;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Collections;

import model.DbConfigs;
import model.DbTable;
import model.User;
import model.User.PERMISSION;

/**
 * add user GUI
 * @author dotnet2
 */
public class addUserJFrame extends javax.swing.JFrame {


	private static final long serialVersionUID = 1L;
	User user = new User();
	ArrayList<DbTable> mTables;

    public addUserJFrame() {
		mTables = new ArrayList<DbTable>();
		StorageManager storageManager = new StorageManager();

		for (DbConfigs db : DbManager.schemas) {
			mTables.addAll(storageManager.getTables(db.getLabel()));
		}
		Collections.sort(mTables, (DbTable o1, DbTable o2) -> o1.name.compareTo(o2.name));
		initComponents();
	}

    /**
     *
     * @return user
     */
    public User getUser() {
		return user;
	}

    /**
     *
     * @param user to be set
     */
    public void setUser(User user) {
		this.user = user;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel_username = new javax.swing.JLabel();
		jLabel_password = new javax.swing.JLabel();
		jButton_add = new javax.swing.JButton();
		jTextField_username = new javax.swing.JTextField();
		jPasswordField = new javax.swing.JPasswordField();
		jLabel_perms = new javax.swing.JLabel();
		jCheckBox_search_permission = new javax.swing.JCheckBox();
		jCheckBox_update_permission = new javax.swing.JCheckBox();
		jCheckBox_delete_permission = new javax.swing.JCheckBox();
		jCheckBox_insert_permission = new javax.swing.JCheckBox();
		jLabel_accessed_tables = new javax.swing.JLabel();
		jLabel_functions = new javax.swing.JLabel();
		jButton_choose_accessed_tables = new javax.swing.JButton();
		jLabel_access_tables_note = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Add user");

		jLabel_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel_username.setText("Username");

		jLabel_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel_password.setText("Password");

		jButton_add.setText("Add");
		jButton_add.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_addActionPerformed(evt);
			}
		});

		jLabel_perms.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel_perms.setText("Permissions");

		jCheckBox_search_permission.setText("Search");

		jCheckBox_update_permission.setText("Update");

		jCheckBox_delete_permission.setText("Delete");

		jCheckBox_insert_permission.setText("Insert");

		jLabel_accessed_tables.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		jLabel_accessed_tables.setText("Accessed tables");

		jLabel_functions.setText("Functions : ");

		jButton_choose_accessed_tables.setText("Choose ..");
		jButton_choose_accessed_tables.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton_choose_accessed_tablesActionPerformed(evt);
			}
		});

		jLabel_access_tables_note.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel_access_tables_note.setForeground(new java.awt.Color(255, 0, 0));
		jLabel_access_tables_note.setText("*if didn't select tables, DbManager will give user access to all tables*");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(22, 22, 22)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(layout.createSequentialGroup().addComponent(jLabel_accessed_tables)
												.addGap(18, 18, 18).addComponent(jButton_choose_accessed_tables,
														javax.swing.GroupLayout.PREFERRED_SIZE, 94,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(layout.createSequentialGroup().addComponent(jLabel_functions)
												.addGap(28, 28, 28).addComponent(jCheckBox_search_permission)))
								.addGap(18, 18, 18).addGroup(
										layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addComponent(jCheckBox_update_permission).addGap(18, 18, 18)
														.addComponent(jCheckBox_delete_permission).addGap(18, 18, 18)
														.addComponent(jCheckBox_insert_permission)
														.addGap(0, 0, Short.MAX_VALUE))
												.addComponent(
														jLabel_access_tables_note, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel_password).addComponent(jLabel_username))
										.addGap(25, 25, 25))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addComponent(jLabel_perms).addGap(18, 18, 18)))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jTextField_username, javax.swing.GroupLayout.DEFAULT_SIZE, 358,
												Short.MAX_VALUE)
										.addComponent(jPasswordField))
								.addGap(0, 0, Short.MAX_VALUE)))
				.addContainerGap())
				.addGroup(layout.createSequentialGroup().addGap(218, 218, 218)
						.addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 165,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(15, 15, 15)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel_username))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel_password))
						.addGap(7, 7, 7).addComponent(jLabel_perms)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jCheckBox_search_permission).addComponent(jCheckBox_update_permission)
								.addComponent(jCheckBox_delete_permission).addComponent(jCheckBox_insert_permission)
								.addComponent(jLabel_functions))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel_accessed_tables)
												.addComponent(jButton_choose_accessed_tables))
										.addGap(13, 13, 13))
								.addComponent(jLabel_access_tables_note, javax.swing.GroupLayout.Alignment.TRAILING))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
						.addComponent(jButton_add).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	@SuppressWarnings("deprecation")
	private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_addActionPerformed
		if (!jTextField_username.getText().isEmpty() && Utils.checkLength(jPasswordField.getText(),
				new Utils().PASSWORD_LENGTH, Utils.SignOperator.BIGGER)) {
			user.setPassword(jPasswordField.getText());
			user.setUsername(jTextField_username.getText());
			ArrayList<PERMISSION> perms = new ArrayList<>();
			if (jCheckBox_search_permission.isSelected()) {
				perms.add(PERMISSION.SEARCH);
			}
			if (jCheckBox_update_permission.isSelected()) {
				perms.add(PERMISSION.UPDATE);
			}
			if (jCheckBox_delete_permission.isSelected()) {
				perms.add(PERMISSION.DELETE);
			}
			if (jCheckBox_insert_permission.isSelected()) {
				perms.add(PERMISSION.INSERT);
			}

			PERMISSION permissions[] = new PERMISSION[perms.size()];

			user.setPermissions(perms.toArray(permissions));
			//user.setAccess_tables(mTables);
			setUser(user);
			dispose();
		} else {
			Utils.showError(Messages.getString("addUserJFrame.err_msg_cannot_login")); //$NON-NLS-1$

		}
	}// GEN-LAST:event_jButton_addActionPerformed

	private void jButton_choose_accessed_tablesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton_choose_accessed_tablesActionPerformed
		TablesJDialog tablesJDialog = new TablesJDialog(mTables);
		tablesJDialog.setVisible(true);

		tablesJDialog.addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosed(WindowEvent e) {
				super.windowClosed(e); // To change body of generated methods, choose Tools | Templates.
				if (tablesJDialog.isDone()) {
					if (!tablesJDialog.getAccessedTables().isEmpty()) {					
						user.setAccess_tables(tablesJDialog.getAccessedTables());
					}
				}
			}
		});
	}// GEN-LAST:event_jButton_choose_accessed_tablesActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton_add;
	private javax.swing.JButton jButton_choose_accessed_tables;
	private javax.swing.JCheckBox jCheckBox_delete_permission;
	private javax.swing.JCheckBox jCheckBox_insert_permission;
	private javax.swing.JCheckBox jCheckBox_search_permission;
	private javax.swing.JCheckBox jCheckBox_update_permission;
	private javax.swing.JLabel jLabel_access_tables_note;
	private javax.swing.JLabel jLabel_accessed_tables;
	private javax.swing.JLabel jLabel_functions;
	private javax.swing.JLabel jLabel_password;
	private javax.swing.JLabel jLabel_perms;
	private javax.swing.JLabel jLabel_username;
	private javax.swing.JPasswordField jPasswordField;
	private javax.swing.JTextField jTextField_username;
	// End of variables declaration//GEN-END:variables
}
