/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JPanel;
import model.DbTable;

/**
 *
 * @author dotnet2
 */
public class InsertPanel extends javax.swing.JPanel {

    /**
     * Creates new form insertPanel
     */
    private static final long serialVersionUID = 1L;

    // required for data show
    private ArrayList<DbTable> mTables;
    String[] table_names;

    // required for data op exe
    private ArrayList<colPanel> colPanels;
    private DbTable selectedTable;

    public ArrayList<colPanel> getColPanels() {
        return colPanels;
    }

    public DbTable getSelectedTable() {
        return selectedTable;
    }

    public void setSelectedTable(DbTable selectedTable) {
        this.selectedTable = selectedTable;
    }

    /**
     * Creates new form insertPanel
     *
     * @param tables
     */
    public InsertPanel(ArrayList<DbTable> tables) {
        this.mTables = tables;
        table_names = new String[mTables.size()];
        int catalog_item_most_common_index = 0;

        for (int i = 0; i < mTables.size(); i++) {
            table_names[i] = mTables.get(i).getName();
            if (mTables.get(i).getName().equals("CATALOG_ITEM")) {
                catalog_item_most_common_index = i;
            }
        }

        jPanel_colsPanel = new JPanel();
        initComponents();
        this.setAutoscrolls(true);

        this.setPreferredSize(
                new Dimension(getToolkit().getScreenSize().width - 100, getToolkit().getScreenSize().height - 200));

        jComboBox_table_names.setSelectedIndex(catalog_item_most_common_index);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_table_name = new javax.swing.JLabel();
        jComboBox_table_names = new javax.swing.JComboBox<>();
        jLabel_data = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel_colsPanel = new javax.swing.JPanel();

        jLabel_table_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_table_name.setText("in table name");

        jComboBox_table_names.setModel(new javax.swing.DefaultComboBoxModel<>(table_names));
        jComboBox_table_names.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_table_namesActionPerformed(evt);
            }
        });

        jLabel_data.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel_data.setText("Data : ");

        jPanel_colsPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel_colsPanel.setAutoscrolls(true);
        jPanel_colsPanel.setLayout(new javax.swing.BoxLayout(jPanel_colsPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanel_colsPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_table_name)
                    .addComponent(jLabel_data))
                .addGap(18, 18, 18)
                .addComponent(jComboBox_table_names, 0, 375, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(188, 188, 188)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_table_name)
                    .addComponent(jComboBox_table_names, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_data)
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_table_namesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_table_namesActionPerformed
        for (int i = 0; i < mTables.size(); i++) {
            if (mTables.get(i).getName()
                    .equals(((String) jComboBox_table_names.getSelectedItem()))) {
                setSelectedTable(mTables.get(i));
                colSetup();
            }
        }
    }//GEN-LAST:event_jComboBox_table_namesActionPerformed
    private void colSetup() {

        colPanels = new ArrayList<>();
        jPanel_colsPanel.removeAll();
        for (int i = 0; i < selectedTable.getCols().size(); i++) {
            colPanel colPanel = new colPanel(selectedTable.getCols().get(i).getName());
            colPanel.setcomboBoxSignOperatorsVisibility(false);
            colPanels.add(colPanel);
            jPanel_colsPanel.add(colPanel);
        }

        revalidate();
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox_table_names;
    private javax.swing.JLabel jLabel_data;
    private javax.swing.JLabel jLabel_table_name;
    private javax.swing.JPanel jPanel_colsPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
