/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dbmanager.ViewManager;
import javax.swing.JTable;

/**
 * preview update from do update process first
 * @author dotnet2
 */
public class previewUpdateJDialog extends javax.swing.JDialog {

	private static final long serialVersionUID = 1L;

    /**
     *
     */
    public boolean confirm = true;

    String[][] mOldData;
    String[] mOldCols;
    String mNewData[][];
    String[] mNewCols;

    /**
     *
     * @param oldData old values to be updated based on
     * @param oldCols old cols to be updated
     * @param newData new values to set on update
     * @param newCols new cols to update
     */
    public previewUpdateJDialog(String[][] oldData, String[] oldCols, String newData[][], String[] newCols) {
        this.mOldData = oldData;
        this.mOldCols = oldCols;
        this.mNewData = newData;
        this.mNewCols = newCols;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_oldData = new javax.swing.JScrollPane();
        jTable_oldData = new javax.swing.JTable();
        jScrollPane_newData = new javax.swing.JScrollPane();
        jTable_newData = new javax.swing.JTable();
        jButton_ok = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preview");

        jTable_oldData.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable_oldData.setModel(new javax.swing.table.DefaultTableModel(
            mOldData,mOldCols
        ));
        jTable_oldData.setRowHeight(24);
        jTable_oldData.setAutoscrolls(true);
        jTable_oldData.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jScrollPane_oldData.setViewportView(jTable_oldData);

        jTable_newData.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable_newData.setModel(new javax.swing.table.DefaultTableModel(
            mNewData,mNewCols
        ));
        jTable_newData.setRowHeight(24);
        jTable_newData.setAutoscrolls(true);
        jTable_newData.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jScrollPane_newData.setViewportView(jTable_newData);

        jButton_ok.setText("OK");
        jButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okActionPerformed(evt);
            }
        });

        jButton_cancel.setText("Cancel");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        jLabel1.setText("OLD");

        jLabel2.setText("NEW");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane_oldData, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane_newData, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(455, 455, 455)
                        .addComponent(jButton_ok)
                        .addGap(101, 101, 101)
                        .addComponent(jButton_cancel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(289, 289, 289))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane_newData, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                    .addComponent(jScrollPane_oldData, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_ok)
                    .addComponent(jButton_cancel))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okActionPerformed
        ViewManager.setNewisExist(true);

        ViewManager.finishingUpdate.start();

        this.dispose();
    }//GEN-LAST:event_jButton_okActionPerformed

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        confirm = false;
        this.dispose();
    }//GEN-LAST:event_jButton_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane_newData;
    private javax.swing.JScrollPane jScrollPane_oldData;
    private javax.swing.JTable jTable_newData;
    private javax.swing.JTable jTable_oldData;
    // End of variables declaration//GEN-END:variables
}
