/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 * to show report about what is happened
 *
 * @author dotnet2
 */
public class reportDialolgPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form reportDialolgPanel
     */
    public reportDialolgPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        show_done = new javax.swing.JToggleButton();
        show_undone = new javax.swing.JToggleButton();
        jScrollPane_short_info = new javax.swing.JScrollPane();
        jTextArea_shortInfo = new javax.swing.JTextArea();
        jScrollPane_done_tables = new javax.swing.JScrollPane();
        jTextArea_done_tables = new javax.swing.JTextArea();
        jScrollPane_undone_tables = new javax.swing.JScrollPane();
        jTextArea_undone_tables = new javax.swing.JTextArea();

        setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        show_done.setText("see done");

        show_undone.setText("see undone");

        jTextArea_shortInfo.setColumns(20);
        jTextArea_shortInfo.setRows(5);
        jScrollPane_short_info.setViewportView(jTextArea_shortInfo);

        jTextArea_done_tables.setColumns(20);
        jTextArea_done_tables.setRows(5);
        jScrollPane_done_tables.setViewportView(jTextArea_done_tables);

        jTextArea_undone_tables.setColumns(20);
        jTextArea_undone_tables.setRows(5);
        jScrollPane_undone_tables.setViewportView(jTextArea_undone_tables);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_short_info)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(show_done, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane_done_tables, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane_undone_tables, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(show_undone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_short_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(show_undone)
                    .addComponent(show_done))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_done_tables, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jScrollPane_undone_tables))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane_done_tables;
    private javax.swing.JScrollPane jScrollPane_short_info;
    private javax.swing.JScrollPane jScrollPane_undone_tables;
    private javax.swing.JTextArea jTextArea_done_tables;
    private javax.swing.JTextArea jTextArea_shortInfo;
    private javax.swing.JTextArea jTextArea_undone_tables;
    private javax.swing.JToggleButton show_done;
    private javax.swing.JToggleButton show_undone;
    // End of variables declaration//GEN-END:variables
}
