/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.util.ArrayList;
import model.DbTable;

/**
 * Update panel GUI
 *
 * @author dotnet2
 */
public class UpdatePanel extends javax.swing.JPanel {

//    JScrollPane jScrollPane_cols2update = null;
//    private JScrollPane jScrollPane_whereCols = null;
    ArrayList<DbTable> mTables;
    String[] table_names;
    // required for data op exe

    private DbTable selectedTable;
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form updatePanel
     *
     * @param tables
     */
    public UpdatePanel(ArrayList<DbTable> tables) {
        this.mTables = tables;
        int catalog_item_most_common_index = 0;
        table_names = new String[mTables.size()];
        for (int i = 0; i < mTables.size(); i++) {
            table_names[i] = mTables.get(i).getName();
            if (mTables.get(i).getName().equals("CATALOG_ITEM")) {
                catalog_item_most_common_index = i;
            }
        }

        initComponents();

        this.setAutoscrolls(true);

        this.setPreferredSize(
                new Dimension(getToolkit().getScreenSize().width - 100, getToolkit().getScreenSize().height - 200));

        jComboBox_table_names.setSelectedIndex(catalog_item_most_common_index);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_cond_union = new javax.swing.ButtonGroup();
        jLabel_table_name = new javax.swing.JLabel();
        jComboBox_table_names = new javax.swing.JComboBox<>();
        jPanel_colsetup = new javax.swing.JPanel();
        jPanel_mainPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        colsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        setUpdatePanel = new javax.swing.JPanel();
        jLabel_cond_union = new javax.swing.JLabel();
        jRadioButton_or = new javax.swing.JRadioButton();
        jRadioButton_and = new javax.swing.JRadioButton();
        jLabel_get = new javax.swing.JLabel();
        jLabel_where = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(48, 25));
        setPreferredSize(new java.awt.Dimension(700, 376));

        jLabel_table_name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_table_name.setText("table name");

        jComboBox_table_names.setModel(new javax.swing.DefaultComboBoxModel<>(table_names));
        jComboBox_table_names.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_table_namesActionPerformed(evt);
            }
        });

        jPanel_mainPanel.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel_mainPanel.setAutoscrolls(true);
        jPanel_mainPanel.setLayout(new java.awt.GridLayout(1, 0));

        colsPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        colsPanel.setAutoscrolls(true);
        colsPanel.setLayout(new javax.swing.BoxLayout(colsPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(colsPanel);

        jPanel_mainPanel.add(jScrollPane1);

        setUpdatePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setUpdatePanel.setAutoscrolls(true);
        setUpdatePanel.setLayout(new javax.swing.BoxLayout(setUpdatePanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane2.setViewportView(setUpdatePanel);

        jPanel_mainPanel.add(jScrollPane2);

        jLabel_cond_union.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_cond_union.setText("Condition uniuon:");

        jRadioButton_or.setText("OR");

        jRadioButton_and.setText("AND");

        jLabel_get.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel_get.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_get.setText("NEW");
        jLabel_get.setAutoscrolls(true);
        jLabel_get.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel_where.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel_where.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_where.setText("OLD");
        jLabel_where.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        buttonGroup_cond_union.add(jRadioButton_and);
        buttonGroup_cond_union.add(jRadioButton_or);
        jRadioButton_or.setSelected(true);

        javax.swing.GroupLayout jPanel_colsetupLayout = new javax.swing.GroupLayout(jPanel_colsetup);
        jPanel_colsetup.setLayout(jPanel_colsetupLayout);
        jPanel_colsetupLayout.setHorizontalGroup(
            jPanel_colsetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_colsetupLayout.createSequentialGroup()
                .addComponent(jLabel_where, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(232, 232, 232)
                .addComponent(jLabel_get, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(245, 245, 245))
            .addGroup(jPanel_colsetupLayout.createSequentialGroup()
                .addGroup(jPanel_colsetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_colsetupLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel_cond_union)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton_or)
                        .addGap(10, 10, 10)
                        .addComponent(jRadioButton_and)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel_mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46))
        );
        jPanel_colsetupLayout.setVerticalGroup(
            jPanel_colsetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_colsetupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_colsetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_get, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_where, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_colsetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_cond_union)
                    .addComponent(jRadioButton_or)
                    .addComponent(jRadioButton_and))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel_table_name)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_colsetup, javax.swing.GroupLayout.PREFERRED_SIZE, 540, Short.MAX_VALUE)
                    .addComponent(jComboBox_table_names, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_table_name)
                    .addComponent(jComboBox_table_names, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel_colsetup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_table_namesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_table_namesActionPerformed

        for (int i = 0; i < mTables.size(); i++) {
            if (mTables.get(i).getName()
                    .equals(((String) jComboBox_table_names.getSelectedItem()))) {
                setSelectedTable(mTables.get(i));

                colSetup();
            }
        }
    }//GEN-LAST:event_jComboBox_table_namesActionPerformed

    /**
     *
     * @param dbTable to be set as selected database table
     */
    protected void setSelectedTable(DbTable dbTable) {
        this.selectedTable = dbTable;
    }

    /**
     * depending on chosen table , draw cols
     */
    private void colSetup() {

        colsPanel.removeAll();
        setUpdatePanel.removeAll();

        colPanels = new ArrayList<>();
        toUpdateColsPanels = new ArrayList<>();

        for (int i = 0; i < selectedTable.getCols().size(); i++) {
            colPanel colPanel = new colPanel(selectedTable.getCols().get(i).getName());
            colPanel to_updateCopy = new colPanel(selectedTable.getCols().get(i).getName());
            to_updateCopy.setcomboBoxSignOperatorsVisibility(false);
            colPanels.add(colPanel);
            colsPanel.add(colPanel);
            toUpdateColsPanels.add(to_updateCopy);
            setUpdatePanel.add(to_updateCopy);
        }

        colsPanel.setAutoscrolls(true);
        setUpdatePanel.setAutoscrolls(true);

        revalidate();
        repaint();
    }

    /**
     *
     * @return full cols to be updated
     */
    public ArrayList<colPanel> getToUpdateColsPanels() {
        return toUpdateColsPanels;
    }

    /**
     *
     * @return selected table
     */
    public DbTable getSelectedTable() {
        return selectedTable;
    }

    /**
     *
     * @return
     */
    public ArrayList<colPanel> getColPanels() {
        return colPanels;
    }

     /**
     *
     * @return String to specify if logic operator between where conditions is "or" or "and"
     */
    public String getCond_where_multiple_cols() {
        if (jRadioButton_or.isSelected()) {
            return Messages.getString("SearchPanel.or"); //$NON-NLS-1$ //$NON-NLS-2$
        } else if (jRadioButton_and.isSelected()) {
            return Messages.getString("SearchPanel.and"); //$NON-NLS-1$
        } else {
            return Messages.getString("SearchPanel.or"); //$NON-NLS-1$ //$NON-NLS-2$
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_cond_union;
    private javax.swing.JPanel colsPanel;
    private javax.swing.JComboBox<String> jComboBox_table_names;
    private javax.swing.JLabel jLabel_cond_union;
    private javax.swing.JLabel jLabel_get;
    private javax.swing.JLabel jLabel_table_name;
    private javax.swing.JLabel jLabel_where;
    private javax.swing.JPanel jPanel_colsetup;
    private javax.swing.JPanel jPanel_mainPanel;
    private javax.swing.JRadioButton jRadioButton_and;
    private javax.swing.JRadioButton jRadioButton_or;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel setUpdatePanel;
    // End of variables declaration//GEN-END:variables

    // required for data op exe
    private ArrayList<colPanel> colPanels;
    private ArrayList<colPanel> toUpdateColsPanels;
}
